- hosts: testnode
  become: yes
  vars: 
    service_user: root
  tasks: 
    - name: copy file to remote host from localhost 
      copy: 
        src: /home/mdasifulhaque/ansible_data/sample/copy/remote-to-remote-host/remote-to-remote.txt
        dest: /home/mdasifulhaque/ansible_data/remote-to-remote.txt
        remote_src: yes
