- hosts: testnode
  become: yes
  tasks: 
    - name: copy file to remote host from localhost 
      copy: 
        src: /home/mdasifulhaque/ansible_data/sample/copy/remote-to-remote-host/
        dest: /home/mdasifulhaque/ansible_data
        remote_src: yes
