- hosts: testnode
  become: yes
  vars: 
    service_user: root

  tasks: 
    - name: copy file to remote host from localhost 
      copy: 
        src: local-to-remote.txt
        dest: $HOME/local-to-remote.txt
