- hosts: testnode
  become: yes
  tasks: 
    - name: copy file to remote host from localhost 
      copy: 
        src: local-to-remote.txt
        dest: /home/sample-data/local-to-remote.txt
        
