---
master:
  hosts:
    master-primary:
      ansible_host: 192.168.10.11
    master-backup:
      ansible_host: 192.168.10.15
    vars:
      ansible_user: root
workers:
  hosts:
    worker-node_one:
      ansible_host: 192.168.10.12
    worker_node_two:
      ansible_host: 192.168.10.13
