- hosts: master
  become: yes
  vars:
    service_user: ansible_service_user
    kubeadm_config_file: /etc/kubernetes/admin.conf
    service_group: wheel
  tasks:
    - name: initialize the cluster
      become_user: "{{ service_user }}"
      become_method: sudo
      shell: kubeadm init --pod-network-cidr 10.244.0.0/16 >> cluster_initialize.txt
      args:
        chdir: $HOME
        creates: cluster_initialize.txt
    - name: sleep for 20 seconds
      wait_for:
        timeout: 20

    - name: create .kube directory
      become_user: "{{ service_user }}"
      become_method: sudo 
      file:
        path: $HOME/.kube
        state: directory
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
        mode: 0755
      become: yes

    - name: check if admin.conf file exist
      become: yes
      stat:
        path: "{{ kubeadm_config_file }}"
      register: kubernetes_admin_config

    - name: copy admin.conf to user's kube config
      become_user: "{{ service_user }}"
      become_method: sudo
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
      when: kubernetes_admin_config.stat.exists

    - name: install pod network
      become_user: "{{ service_user }}"
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
