- hosts: all
  become: yes
  become_user: "{{ service_user }}"
  become_method: sudo
  gather_facts: true
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{join_command_raw.stdout_lines[0]}}"

- hosts: workers
  tasks:
    - name: join cluster
      become: yes
      become_user: "{{ service_user }}"
      become_method: sudo
      shell: "{{hostvars['master'].join_command}} --ignore-preflight-errors-all >> node_joined.txt"
      ignore_errors: true
      args:
        chdir: $HOME
        creates: node_joined.txt
