- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: get join command
      #become_user: ansible_service_user
      #become_method: sudo
      shell: kubeadm token-create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{join_command_raw.stouts_lines[0]}}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      become_user: ansible_service_user
      become_method: sudo
      shell: "{{hostvars['master'].join_command}} --ignore-preflight-errors-all >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
