- hosts: master
  gather_facts: false
  vars:
    kubeadm_config_file: /etc/kubernetes/admin.conf
    service_user: ansible_service_user
    service_group: wheel
  tasks:
    - name: initialize the cluster
      become: yes
      become_method: sudo
      remote_user: ansible_service_user
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.10.15  --v=6
      register: result
      until: result.stdout.find("Your Kubernetes control-plane has initialized successfully!") != -1
      retries: 1
      delay: 20

    - debug: var=result.stdout_lines

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        owner: "{{service_user}}"
        group: "{{service_group}}"
        mode: 0755
      become: yes
      become_method: sudo
      remote_user: ansible_service_user

    - name: check if admin.conf file exists
      stat:
        path: "{{ kubeadm_config_file }}"
      register: kubernetes_admin_config

    - name: copy admin.conf to user's kube config
      become: yes
      become_user: "{{ service_user }}"
      become_method: sudo
      copy:
        src: "{{kubeadm_config_file}}"
        dest: $HOME/.kube/config
        remote_src: yes
        owner: "{{ service_user }}"
      when: kubernetes_admin_config.stat.exists
